version: "3.3"

services:
  service:
    build: service
    network_mode: "host"
    ports:    
      - "8081:8081"

  linkerd:
    build: linkerd
    network_mode: "host"
    ports:
      - "8080:8080"
      - "9990:9990"
