version: "3.3"

services:
  service:
    build: service
    network_mode: "host"
    ports:    
      - "8081:8081"

  linkerd:
    build: linkerd
    network_mode: "host"
    ports:
      - "8080:8080"
      - "9990:9990"

  kong:
    build: kong
    network_mode: "host"
    ports:
      - "8000:8000"

  zipkin:
    image: openzipkin/zipkin
    network_mode: "host"
    ports:
      - "9411:9411"
