admin:
  port: 9990
  ip: 0.0.0.0

routers:
  - protocol: http
    dtab: /svc => /$/inet/127.1/8081
    servers:
      - port: 8080
        ip: 0.0.0.0

telemetry:
  - kind: io.l5d.zipkin
    host: http://localhost
    port: 9411
    sampleRate: 1.00
