admin:
  port: 9990
  ip: 0.0.0.0

routers:
  - protocol: http
    dtab: /svc => /$/inet/127.1/8081
    servers:
      - port: 8080
        ip: 0.0.0.0

telemetry:
  - kind: io.zipkin.http
    host: localhost:9411
    initialSampleRate: 1.00
